server {
    listen 8888;
    server_name localhost;
    root /usr/share/nginx/html;
    autoindex off;

    types {
        text/html html;
        application/javascript mjs;
        text/css css;
        image/svg+xml svg;
    }

    location / {
        try_files $uri $uri/ /viewer.html;
        index viewer.html;
    }

    error_page 404 /viewer.html;
}
